### ISSUE TITLE
Undocumented extension types

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#514] opened 2019-04-19 05:37 UTC
- [x] api
- [x] pages
- [x] collection filters

**Comment by texnixe** [comment] 2019-08-03 14:55
@distantnative What is the pages extension or how does it work? I thought it was intended to register pages from a plugin but couldn't find a way to achieve that nor can I find anything regarding such a feature in the changelog. Do you have any information for me? Otherwise, we can close this, I think

**Comment by distantnative** [comment] 2019-08-06 07:51
Apparently you can register pages via this extension: 
https://github.com/getkirby/kirby/blob/master/src/Cms/AppPlugins.php#L332-L341
and
https://github.com/getkirby/kirby/blob/master/src/Cms/Pages.php#L308

**Comment by texnixe** [comment] 2019-08-06 08:20
Yes, I get that. But do you know how?

**Comment by distantnative** [comment] 2019-08-06 08:23
From the code I'd assume

```php
Kirby::plugin('my/plugin', [
  'pages' => [
    [
      'slug' => 'new-page'
      //..
    ]
  ]
]);
```

But couldn't test it yet.

**Comment by texnixe** [comment] 2019-10-13 18:08
I get some sort of result if I modify the above snippet like this:

```
<?php 
Kirby::plugin('my/plugin', [
    'pages' => [
        'new-page' => [   
            'slug' => 'new-page',
            'parent' => site(),
            'template' => 'default',
            'content' => [
                'title' => 'Hello'
            ],
       ]
    ]
]);
```
But when I try to open the URL `new-page` in the browser, the result is a JSON string. To be able to document this, I need some more information.

**Comment by lukasbestle** [comment] 2019-11-10 19:23
@texnixe The following works for me:

```php
<?php

Kirby::plugin('my/plugin', [
    'pages' => [
        'new-page' => new Page([
            'slug' => 'new-page',
            'template' => 'default',
            'content' => [
                'title' => 'Hello'
            ]
       ])
    ]
]);
```

**Comment by texnixe** [comment] 2019-11-10 19:28
@lukasbestle Yes, that work, thanks. I thought I had tested all possible variants... 🤷‍♀.

**Closed as completed** 2019-11-10 20:06 UTC
Labels: needs: information ❓
