### ISSUE TITLE
Reference Cookbook in Guide

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/getkirby.com#635] opened 2019-07-31 11:05 UTC
I've been checking out basic concept in the Kirby guides and was left with the feeling "wow, that was a bit brief" and only later noticed that the more in-depth information resided inside the cookbook area. Example: 

- I was looking at the template basics in the guide, https://getkirby.com/docs/guide/templates/basics.
- I was having questions about basic PHP concepts how to handle loops and conditions.
- I didn't understand there was a whole section of cookbook entries regarding templating, see https://getkirby.com/docs/cookbook?category=templating.
- And especially I was missing the "Kirby template 101" at https://getkirby.com/docs/cookbook/templating/php-templates.

It would be very helpful, if those cookbook entries were featured prominently on top of the related guide page. Maybe using a magazine style insert having a prominent card for the first 2 or 3 three entries followed by a link to the filtered cookbook. The Kirby site already has a few layouts in that sense that certainly could be adapted and reused:

<img width="946" alt="grafik" src="https://user-images.githubusercontent.com/25466/62206974-373fc000-b393-11e9-9442-c49bf299298d.png">
<img width="946" alt="grafik" src="https://user-images.githubusercontent.com/25466/62207040-66eec800-b393-11e9-9b41-fec0579f6a72.png">
<img width="944" alt="grafik" src="https://user-images.githubusercontent.com/25466/62207012-53436180-b393-11e9-9ec3-b1cde7f24d3b.png">

As a first step, a textual link would be great, too. But I'd argue a more visual approach to these links will make sure users don't overlook the tutorials.

**Comment by texnixe** [comment] 2019-07-31 12:09
Yep, that's been my thinking as well.

**Comment by texnixe** [comment] 2019-08-05 20:39
That's actually a duplicate of https://github.com/getkirby/getkirby.com/issues/567, so I'm closing this.

**Closed as completed by texnixe** 2019-08-05 20:39 UTC
