### ISSUE TITLE
Docs do not include all available parameters for blueprint field options

### ISSUE THREAD

**Issue by Splendorr** [getkirby/getkirby.com#312] opened 2019-02-12 01:55 UTC
I'm going to type out how confusing I've found a few aspects of the documentation. I'm not angry or trying to belabor the points; I'm just trying to clearly state some of the things I just tried to find in the docs, and how long it took me to track down the pieces of knowledge that eventually led me to infer some very clean and simple solutions.

So, I'm having a hard time figuring out how to use the new blueprints in V3. There are many places where an option is listed with a description of what it does, but not the parameters it accepts. For example, the Files field (https://getkirby.com/docs/reference/panel/fields/files) says there's a "size" option, as a string, described as "Layout size for cards". However, I can't find a list of valid parameters for "size" anywhere in the docs. I found one example in the Starterkit that uses "small", but that's it. 

For Files, there are also missing parameters for "image" (it says there are image options, but not what they are).

There are also many pages with _some_ examples, but which don't connect the dots. Let's say I only want to show images or videos in a Files field. In the docs, I see that there's a query option, including the default setting. It would be nice to have a link to the Query Language guide page (https://getkirby.com/docs/guide/blueprints/query-language), since that's not something I ever encountered in V2. Once here, though, there are no examples for how to use `query:` with the `files` field. Maybe that's okay; I can infer from "Querying Options in Fields" that I could try querying within `files`. But how do I select a subset of file types? The only place "filterBy" is mentioned is in the Syntax example. There's no link to the filterBy docs; so I have to search for "filterBy", which might land me on the Filtering Compendium cookbook page (but didn't in my initial search), which is pretty thorough but not written in the Query Language, and also doesn't list all valid file types to query. Finally I made my way to https://getkirby.com/docs/reference/objects/files/filter-by which seemed to suggest that I should use something like:

`$files = $page->files()->filterBy('type', '!=', 'document');`

which led me to guessing that I could use `query: page.files.filterBy('type', '==', 'image')` and `query: page.files.filterBy('type', '==', 'video')`.

But it wasn't until I started typing all of this out and trying to retrace how gently frustrating this was that I realized (again, by inference, not by any direct example) that these are apparently equivalent to `query: page.images` and `query: page.videos`! 

And _those_ are extremely convenient, compact ways to filter the options available in a Files field! However, I _still_ don't know what the valid strings are for `size` in a `files` field.

So, adding that sort of thing to the docs might be really helpful. I'll consider doing it myself when I'm not in the middle of my workday.

**Comment by texnixe** [comment] 2019-02-12 10:19
Thank a lot for your feedback. I understand your frustration and the documentation definitely still has some loose ends that we have to tackle. Understanding where you have problems helps us to achieve this.

**Comment by texnixe** [comment] 2019-02-12 20:23
I've added examples for the query option, the rest we have to do in the Kirby source code.

**Comment by Splendorr** [comment] 2019-02-13 20:52
Thank you, @texnixe ! I appreciate the changes, and will also try to make my own contributions to the docs as I come across other things that could be improved. I really like Kirby, and have been using V2 for almost 3 years. V3 has been great; I just want myself and everyone else to be able to learn and use it to its full awesome potential! Y'all are doing great work.

**Comment by texnixe** [comment] 2019-03-05 00:19
I'll close this now, because the missing option descriptions are a duplicate of https://github.com/getkirby/getkirby.com/issues/165

**Closed by texnixe** 2019-03-05 00:19 UTC
