### ISSUE TITLE
Document column types (relevant for fiel preview types)

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#2196] opened 2024-02-06 18:39 UTC
https://getkirby.com/docs/reference/panel/sections/pages#layout missing many types and not very clear info on what it does

**Comment by texnixe** [comment] 2024-02-19 06:09
Duplicate of https://github.com/getkirby/getkirby.com/issues/2175

**Closed as completed by texnixe** 2024-02-19 06:09 UTC
