### ISSUE TITLE
Reference: API show action and method in overview

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#211] opened 2019-01-19 08:50 UTC

**Comment by texnixe** [comment] 2019-08-02 19:25
Is this a duplicate of #210 or something different?

**Comment by texnixe** [comment] 2019-08-03 15:34
@distantnative What does this mean and is it still relevant?

**Comment by distantnative** [comment] 2019-08-03 15:52
It is. In the reference overview you only see the API endpoints but not what they are for or what method you have to call them with. So with some you will have the exact same endpoint listed, no clue which one will lead you to which explanation.

**Comment by texnixe** [comment] 2019-08-03 16:15
Ah, ok.

**Closed** 2019-08-07 13:43 UTC
Labels: type: enhancement ✨, type: styles 🌈
