### ISSUE TITLE
Wrong link to anchor

### ISSUE THREAD

**Issue by malvese** [getkirby/getkirby.com#57] opened 2015-03-15 16:47 UTC
Some links in the docs' table of contents don't work, because dashes are added in the link and not the anchor

I found two occurrences at http://getkirby.com/docs/advanced/customized-folder-setup, e.g:

The link is #multisite-setup while the anchor is "multi-site-setup".
Same for the #site-php link on the same page.

Not sure why it happens though. It may have to do with the new Markdown parser, that escapes chars in a different way than str::slug()?

**Comment by vyder** [comment] 2015-03-16 12:24
I think this issue is a duplicate of #24

**Closed** 2015-03-30 11:35 UTC
