### ISSUE TITLE
Error in plugin search page

### ISSUE THREAD

**Issue by ghost** [getkirby/getkirby.com#943] opened 2020-04-22 17:37 UTC
Searching  _Video_ in plugin page gives 3 results. In these results there is a plugin from _schnti_ and an other from _hashandsalt_ . Opening both links to preview plugin gives the same content (_hashandsalt plugin_) but not the same url.

**Comment by texnixe** [comment] 2020-04-22 17:50
Thanks for reporting. the plugins have the same slug, so there's something going wrong with fetching the right repo info.

**Comment by texnixe** [comment] 2020-04-22 21:36
Weird, in my local copy everything is correct. Maybe a caching issue on the server.

**Comment by texnixe** [comment] 2020-05-24 13:50
Closing this as it works now.

**Comment by texnixe** [comment] 2020-05-31 07:32
Hm, weird, still not fixed online, although locally it works ok, @bastianallgeier?

**Comment by distantnative** [comment] 2021-02-21 15:50
We're using different cache types locally vs. online. Maybe that's related?

**Comment by distantnative** [comment] 2021-02-21 15:53
I would assume that this line is the origin:
https://github.com/getkirby/getkirby.com/blob/master/site/models/plugin.php#L17

Just using the `slug` is probably the cause. Instead we might use `id()`, @bastianallgeier?

**Comment by distantnative** [comment] 2021-02-21 17:30
Yep, I think this solved it.

**Closed as completed by distantnative** 2021-02-21 17:30 UTC
